# Notes generated by GitHub Copilot
import cv2
import numpy as np
import os
from rembg import remove


# Define a function to process a single image and return the smallest circumscribed square
def process_image(image_path, output_path):
    # Read image
    img = cv2.imread(image_path)

    # Use remove function to segment the seed from the background
    output = remove(img)

    # Convert the result to grayscale for contour detection
    gray = cv2.cvtColor(output, cv2.COLOR_BGR2GRAY)

    # Threshold to create a binary image (necessary for contour detection)
    _, binary = cv2.threshold(gray, 1, 255, cv2.THRESH_BINARY)

    # Find contours of the segmented seed
    contours, _ = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    if contours:
        # Find the largest contour (assuming it's the seed)
        c = max(contours, key=cv2.contourArea)

        # Get the bounding rectangle of the contour
        x, y, w, h = cv2.boundingRect(c)

        # Calculate the center of the bounding rectangle
        cx = x + w // 2
        cy = y + h // 2

        # Calculate the side length of the minimum enclosing square
        side_length = max(w, h)

        # Find the top-left corner of the square
        square_x = max(0, cx - side_length // 2)
        square_y = max(0, cy - side_length // 2)

        # Crop the image to the square
        crop_img = output[square_y:square_y + side_length, square_x:square_x + side_length]

        # Resize the cropped image to 299x299
        final_img = cv2.resize(crop_img, (299, 299))

        # Save the final image
        cv2.imwrite(output_path, final_img)

        print(f"Processed and saved: {output_path}")
    else:
        print(f"No contours found in {image_path}.")


# process_image('./original_dataset/IMG_2934.jpg', './process_dataset/IMG_2934.jpg')

# Define a function to process all images in a folder
def batch_process_images(in_folder, out_folder):
    if not os.path.exists(out_folder):
        os.makedirs(out_folder)

    for filename in os.listdir(in_folder):
        if filename.endswith(".jpg"):  # (".jpg", ".png", ".jpeg")
            input_path = os.path.join(in_folder, filename)
            output_path = os.path.join(out_folder, filename)
            process_image(input_path, output_path)


input_folder = './full_original_dataset'
output_folder = './process_dataset'

# Process images in batches
batch_process_images(input_folder, output_folder)

