# Notes generated by GitHub Copilot
import cv2
import numpy as np
import os
from rembg import remove


def process_image(image_path, output_path):
    img = cv2.imread(image_path)

    img_no_bg = remove(img)

    gray = cv2.cvtColor(img_no_bg, cv2.COLOR_BGR2GRAY)

    _, binary = cv2.threshold(gray, 1, 255, cv2.THRESH_BINARY)

    contours, _ = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    if contours:
        c = max(contours, key=cv2.contourArea)

        x, y, w, h = cv2.boundingRect(c)

        side_length = max(w, h)

        cx = x + w // 2
        cy = y + h // 2

        square_x = max(0, cx - side_length // 2)
        square_y = max(0, cy - side_length // 2)

        crop_img = img[square_y:square_y + side_length, square_x:square_x + side_length]

        final_img = cv2.resize(crop_img, (299, 299))

        cv2.imwrite(output_path, final_img)

        print(f"Processed and saved: {output_path}")
    else:
        print(f"No contours found in {image_path}.")

# Define a function to process all images in a folder
def batch_process_images(in_folder, out_folder):
    if not os.path.exists(out_folder):
        os.makedirs(out_folder)

    for filename in os.listdir(in_folder):
        if filename.endswith(".jpg"):  # (".jpg", ".png", ".jpeg")
            input_path = os.path.join(in_folder, filename)
            output_path = os.path.join(out_folder, filename)
            process_image(input_path, output_path)


input_folder = './full_original_dataset'
output_folder = './process_dataset_without_cutout'

# Process images in batches
batch_process_images(input_folder, output_folder)
